<?php
/**
 * Created by PhpStorm.
 * User: minhhai
 * Date: 2/15/17
 * Time: 09:41
 */

namespace Apps\YNC_Affiliate\Controller\Admin;

use Phpfox;
use Phpfox_Error;
use Phpfox_Plugin;


class EditCommissionRuleController extends \Admincp_Component_Controller_App_Index
{
    public function process()
    {
        parent::process(); // TODO: Change the autogenerated stub
        if($iResetId = $this->request()->getInt('reset'))
        {
            $iGroupId = $this->request()->getInt('group');
            if(Phpfox::getService('yncaffiliate.commissionrule.process')->clearRuleDetail($iResetId))
            {
                $this->url()->send('admincp.yncaffiliate.commission-rule',['group' => $iGroupId],_p('commission_rule_clear_successfully'));
            }
        }
        $this->template()->setTitle(_p('edit_commission_rule'))
            ->setBreadCrumb(_p('edit_commission_rule'));
        $iRuleMapId = $this->request()->getInt('rulemap');
        $iRuleId = $this->request()->getInt('rule');
        $iGroupId = $this->request()->getInt('group');
        if(!$iRuleMapId || !$iRuleId)
        {
            $this->url()->send('admincp.yncaffiliate.commission-rule',_p('invalid_params'));
        }
        $aRuleDetail = Phpfox::getService('yncaffiliate.commissionrule.commissionrule')->getRuleDetail($iRuleId);
        $iRuleMapActive = Phpfox::getService('yncaffiliate.commissionrule.commissionrule')->getRuleMap($iRuleMapId,'is_active');
        $aMapDetail = Phpfox::getService('yncaffiliate.commissionrule.commissionrule')->getCommissionRuleDetail($iRuleMapId);
        if($aVals = $this->request()->getArray('val'))
        {
            $aMapDetail = [];
            foreach ($aVals as $key => $aVal)
            {
                if($key != 'is_active')
                    $aMapDetail[] = $aVal;
            }
            if($this->_validate($aVals))
            {
                if(Phpfox::getService('yncaffiliate.commissionrule.process')->updateRuleForGroup($aVals,$iRuleMapId))
                {
                    $this->url()->send('admincp.yncaffiliate.commission-rule',['group' => $iGroupId],_p('commission_rule_updated_successfully'));
                }
            }
        }
        $this->template()->assign([
            'aMapDetail' => $aMapDetail,
            'aRuleDetail' => $aRuleDetail,
            'iRuleMapActive' => $iRuleMapActive,
            'iRuleMapId' => $iRuleMapId,
            'iGroupId'  => $iGroupId,
            'iRuleId' => $iRuleId
        ]);
    }

    public function _validate($aVals)
    {
        for ($i = 1;$i <= 5; $i ++)
        {
            if(!is_numeric($aVals['level_'.$i]['rule_value']) && $aVals['level_'.$i]['rule_value'] != '')
            {
                return Phpfox_Error::set(_p('please_enter_a_valid_number_for_commission_value'));
            }
        }

        return Phpfox_Error::isPassed();
    }
}